// <auto-generated />
using System;
using CursoNetCoreCarService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarServiceFronted.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CarServiceFronted.Models.Car", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Model");

                    b.HasKey("ID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CursoNetCoreCarService.Models.CarService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CarID");

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Status");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CursoNetCoreCarService.Models.CarService", b =>
                {
                    b.HasOne("CarServiceFronted.Models.Car")
                        .WithMany("Services")
                        .HasForeignKey("CarID");
                });
#pragma warning restore 612, 618
        }
    }
}
